name: Hugging Face Model Management

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  pull_model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Pull Hugging Face Model
        run: |
          python tasks/huggingface_tasks.py pull_model --model_name=gpt2 --save_directory=./models/gpt2

  push_model:
    needs: pull_model
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Push Hugging Face Model
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python tasks/huggingface_tasks.py push_model --model_directory=./models/gpt2 --repo_name=your-username/your-repo-name
