name: Manage Hugging Face Repo with Enhancements

on:
  push:
    branches:
      - main

jobs:
  manage-repo:
    runs-on: ubuntu-latest

    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      HF_REPO_URL: ${{ secrets.HF_REPO_URL }}
      HF_REPO_TYPE: "model"

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        pip install huggingface_hub

    - name: Train Model (Optional)
      run: |
        python train_model.py
        mv trained_model ./hf-repo/

    - name: Push Changes
      run: |
        huggingface-cli repo clone "$HF_REPO_URL" ./hf-repo
        cp -r your-local-files/* ./hf-repo/
        cd ./hf-repo
        git add .
        git commit -m "Updated repository with trained model"
        git push

    - name: Add Version Tag
      run: |
        DATE_TAG=$(date +%Y.%m.%d-%H%M%S)
        git tag "v$DATE_TAG"
        git push origin "v$DATE_TAG"
