name: Lint and Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Lint Code
        run: |
          source venv/bin/activate
          flake8 fab_tasks/ tests/
          black --check fab_tasks/ tests/

      - name: Run Tests
        run: |
          source venv/bin/activate
          pytest tests/

      - name: Upload Coverage Report (Optional)
        uses: codecov/codecov-action@v3

deploy:
  needs: [lint-and-test]
  runs-on: ubuntu-latest

  steps:
    - name: Set Up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: docker build -t your-app-name .

    - name: Push to Docker Hub
      run: docker push your-dockerhub-account/your-app-name
